// contain some methods that will be reused several times

// to import elliptic module, generate the private key and public key
const EC = require('elliptic').ec;
const SHA256 = require('crypto-js/sha256');
const ec = new EC('secp256k1');

const uuidV1 = require('uuid/v1');

class ChainUtil {
    static genKeyPair() {
        // with this, we can get the private and public key generated by this keypair
        return ec.genKeyPair();
    }

    static id() {
        return uuidV1();
    }

    static hash(data) {
        return SHA256(JSON.stringify(data)).toString();
    }

    static verifySignature(publicKey, signature, dataHash) {
        return ec.keyFromPublic(publicKey,'hex').verify(dataHash, signature);
    }
}

module.exports = ChainUtil;